# Generated by Django 3.1.4 on 2021-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creatted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
