# Generated by Django 3.1.4 on 2021-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210124_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookShop',
        ),
    ]
